[project]
name = 'counter'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 3
epoch = 3.0

[contracts.hello-stacks]
path = 'contracts/hello-stacks.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
